### ISSUE TITLE
Briefly explain Sphinx in the readme.rst?

### ISSUE THREAD

**Issue by kheremos** [russellballestrini/botoform#3]
I followed a link that said, "Sphinx" to this page:
https://github.com/russellballestrini/botoform/tree/master/docs

And it says that it will set up and configure a Sphinx project, but no link or one-liner saying what Sphinx is.  Granted, I've used Python in a very limited capacity before, and this is likely tribal knowledge.  But just a clue or link would help a lot in case some other novice comes around?

Assuming it's this:
https://pypi.python.org/pypi/Sphinx

**Comment by russellballestrini** [comment]
Yup, we should do that.

**Comment by kheremos** [comment]
Thanks!

**Comment by russellballestrini** [comment]
@kheremos welcome, please review the difference here: https://github.com/russellballestrini/botoform/tree/master/docs#sphinx

**Comment by kheremos** [comment]
Yep, I did right before I extended gratitude. Concise, clear and useful.  Thank you for humoring a Python novice!
